route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'email-admin'

receivers:
- name: 'email-admin'
  email_configs:
  - to: 'user@gmail.com'
    from: 'email-remitente@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'email-remitente@gmail.com'
    auth_identity: 'email-remitente@gmail.com'
    auth_password: 'password-de-aplicacion'
